# it defines a service named "main" that uses the "miniconda3" image, sets an environment variable DATASETS_PATH, 
# sets the context and Dockerfile to build the image and maps the ssh and datasets folder from the host to the container.

# By adding the DATASETS_PATH as an environment variable, user can add a different dataset path when
# they run the docker_compose by running:
# >> docker-compose up -e DATASETS_PATH=/path/to/new/datasets

# It's also good to note that the environment keys in the compose file are passed to the container as 
# environment variables, that means the $DATASETS_PATH variable in the container will be /datasets

version: '3.3'

services:
  datascience:
    container_name: datascience
    image: datascience
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /storage/artinmajdi/:/home/
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-caps:/dev/nvidia-caps
    network_mode: host
    tty: true
    stdin_open: true
    