#  -------------   Getting Miniconda image   -------------
FROM continuumio/miniconda3:latest


#set the work directory to /home 
WORKDIR /app

# Update the PATH environment variable to include the Miniconda3 binary directory
ENV PATH /opt/conda/bin:$PATH

ENV USERNAME artinmajdi
RUN useradd -ms /bin/bash $USERNAME


#  -------------   Creating the conda environment   -------------

# Create a new conda environment and install required packages
ENV CONDA_ENV_NAME main
RUN conda create --name $CONDA_ENV_NAME python=3.9 psycopg2

# The command below acts similar to "source activate main"
SHELL ["conda", "run", "-n", "main", "/bin/bash", "-c"]
ENV PATH /opt/conda/envs/$CONDA_ENV_NAME/bin:$PATH


# Install SSH packages and configure the SSH daemon
RUN apt-get update && apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo 'root:password' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config


#  -------------   Installing the package dependencies   -------------

# Installing PyTorch dependencies
RUN conda install -c pytorch pytorch torchvision

# Installing Tensorflow dependencies
RUN conda install -c conda-forge tensorflow tensorflow-hub tensorflow-datasets keras

# Installing Other dependencies
RUN conda install -c conda-forge gitpython scikit-learn scikit-image seaborn matplotlib numpy pandas tqdm wget

# Installing Jupyter dependencies
RUN conda install -c conda-forge ipywidgets notebook pysftp psycopg2

# Installing MLFlow dependencies
RUN conda install -c conda-forge mlflow

# Installing CrowdKit & TorchXRayVision Packages
RUN pip install crowd-kit torchxrayvision



#  -------------   Cloning the repository   -------------

# Add your GitHub repository as a known host
# RUN eval "$(ssh-agent -s)"
# RUN ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts

# Change the permissions of the private key
# RUN chmod 600 /root/.ssh/

# Clone your private GitHub repository
# RUN git clone git@github.com:artinmajdi/chest_xray_private_main.git --depth 1
# https://github.com/artinmajdi/chest_xray_private_main.git


#  ------   Exposing the ports   ------

# Expose the necessary ports
# EXPOSE 22
# EXPOSE 5000

# Define the command that starts the application and SSH daemon
# CMD ["/usr/sbin/sshd", "-D"] 


# docker build -t mcnd -f Docker/Dockerfile_miniconda .
# docker run -it -v ~/.ssh:/root/.ssh -v /Users/personal-macbook/Documents/PhD/code/my_main_code/main/datasets:/datasets mcnd
